// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RihalChallenge.Models;

namespace RihalChallenge.Migrations
{
    [DbContext(typeof(SqliteDbContext))]
    [Migration("20220414135531_Initial-Commit")]
    partial class InitialCommit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.16");

            modelBuilder.Entity("RihalChallenge.Models.Classes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("class_name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            class_name = "Dot.Net"
                        },
                        new
                        {
                            Id = 2,
                            class_name = "AI"
                        },
                        new
                        {
                            Id = 3,
                            class_name = "ML"
                        },
                        new
                        {
                            Id = 4,
                            class_name = "Laravel"
                        },
                        new
                        {
                            Id = 5,
                            class_name = "Game Development"
                        });
                });

            modelBuilder.Entity("RihalChallenge.Models.Countries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Oman"
                        },
                        new
                        {
                            Id = 2,
                            Name = "KSA"
                        },
                        new
                        {
                            Id = 3,
                            Name = "UAE"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Kuwait"
                        });
                });

            modelBuilder.Entity("RihalChallenge.Models.Students", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Class_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Country_id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date_of_birth")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Class_id = 3,
                            Country_id = 5,
                            Date_of_birth = new DateTime(1909, 12, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Florida Hodkiewicz"
                        },
                        new
                        {
                            Id = 2,
                            Class_id = 4,
                            Country_id = 5,
                            Date_of_birth = new DateTime(1903, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Ms. Eriberto Dino Rath II"
                        },
                        new
                        {
                            Id = 3,
                            Class_id = 3,
                            Country_id = 4,
                            Date_of_birth = new DateTime(1996, 8, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Madelyn Smith"
                        },
                        new
                        {
                            Id = 4,
                            Class_id = 1,
                            Country_id = 1,
                            Date_of_birth = new DateTime(1990, 8, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Gisselle Cassin"
                        },
                        new
                        {
                            Id = 5,
                            Class_id = 4,
                            Country_id = 1,
                            Date_of_birth = new DateTime(1909, 9, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Ashlynn Goldner"
                        },
                        new
                        {
                            Id = 6,
                            Class_id = 3,
                            Country_id = 2,
                            Date_of_birth = new DateTime(1955, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Eric Yundt"
                        },
                        new
                        {
                            Id = 7,
                            Class_id = 3,
                            Country_id = 1,
                            Date_of_birth = new DateTime(1962, 10, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Selina Welch"
                        },
                        new
                        {
                            Id = 8,
                            Class_id = 1,
                            Country_id = 3,
                            Date_of_birth = new DateTime(1922, 4, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Mrs. Corrine Corene Emard"
                        },
                        new
                        {
                            Id = 9,
                            Class_id = 5,
                            Country_id = 3,
                            Date_of_birth = new DateTime(1980, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Vicente Shanahan Jr."
                        },
                        new
                        {
                            Id = 10,
                            Class_id = 3,
                            Country_id = 5,
                            Date_of_birth = new DateTime(1960, 10, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Marguerite Johann Mann PhD"
                        },
                        new
                        {
                            Id = 11,
                            Class_id = 5,
                            Country_id = 3,
                            Date_of_birth = new DateTime(1960, 12, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Friedrich Cummerata"
                        },
                        new
                        {
                            Id = 12,
                            Class_id = 1,
                            Country_id = 2,
                            Date_of_birth = new DateTime(1981, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Ms. Rocky Amalia Quigley"
                        },
                        new
                        {
                            Id = 13,
                            Class_id = 3,
                            Country_id = 4,
                            Date_of_birth = new DateTime(1911, 2, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Mr. Annamarie Pierce Spencer III"
                        },
                        new
                        {
                            Id = 14,
                            Class_id = 3,
                            Country_id = 5,
                            Date_of_birth = new DateTime(1912, 6, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Dean Lueilwitz V"
                        },
                        new
                        {
                            Id = 15,
                            Class_id = 3,
                            Country_id = 2,
                            Date_of_birth = new DateTime(1986, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Keven Grady DDS"
                        },
                        new
                        {
                            Id = 16,
                            Class_id = 3,
                            Country_id = 1,
                            Date_of_birth = new DateTime(2019, 3, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Alfonzo Kenny Konopelski Jr."
                        },
                        new
                        {
                            Id = 17,
                            Class_id = 4,
                            Country_id = 3,
                            Date_of_birth = new DateTime(1991, 9, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Halie Cassin"
                        },
                        new
                        {
                            Id = 18,
                            Class_id = 3,
                            Country_id = 4,
                            Date_of_birth = new DateTime(2009, 8, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Otilia Wiegand"
                        },
                        new
                        {
                            Id = 19,
                            Class_id = 4,
                            Country_id = 5,
                            Date_of_birth = new DateTime(1944, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Arlo Miles Crona III"
                        },
                        new
                        {
                            Id = 20,
                            Class_id = 5,
                            Country_id = 4,
                            Date_of_birth = new DateTime(1991, 1, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Makenna Thompson"
                        },
                        new
                        {
                            Id = 21,
                            Class_id = 2,
                            Country_id = 5,
                            Date_of_birth = new DateTime(1930, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Selina Gianni Volkman I"
                        },
                        new
                        {
                            Id = 22,
                            Class_id = 1,
                            Country_id = 4,
                            Date_of_birth = new DateTime(1925, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Mr. Isaias Casper"
                        },
                        new
                        {
                            Id = 23,
                            Class_id = 4,
                            Country_id = 4,
                            Date_of_birth = new DateTime(1916, 10, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Dr. Reanna Bogan"
                        },
                        new
                        {
                            Id = 24,
                            Class_id = 3,
                            Country_id = 2,
                            Date_of_birth = new DateTime(1990, 9, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Albertha Zemlak"
                        },
                        new
                        {
                            Id = 25,
                            Class_id = 5,
                            Country_id = 4,
                            Date_of_birth = new DateTime(2006, 8, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Miss Quincy Freddy Lesch DDS"
                        },
                        new
                        {
                            Id = 26,
                            Class_id = 2,
                            Country_id = 4,
                            Date_of_birth = new DateTime(1982, 4, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Maurice Theresia Larkin Jr."
                        },
                        new
                        {
                            Id = 27,
                            Class_id = 1,
                            Country_id = 4,
                            Date_of_birth = new DateTime(1929, 7, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Sid Fay"
                        },
                        new
                        {
                            Id = 28,
                            Class_id = 4,
                            Country_id = 2,
                            Date_of_birth = new DateTime(1996, 10, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Ms. Tevin Frida Renner DVM"
                        },
                        new
                        {
                            Id = 29,
                            Class_id = 3,
                            Country_id = 5,
                            Date_of_birth = new DateTime(1940, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Miss Merlin Mia Wiza"
                        },
                        new
                        {
                            Id = 30,
                            Class_id = 2,
                            Country_id = 3,
                            Date_of_birth = new DateTime(1915, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Miss Rita Dooley"
                        },
                        new
                        {
                            Id = 31,
                            Class_id = 2,
                            Country_id = 2,
                            Date_of_birth = new DateTime(1916, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Graciela Harvey"
                        },
                        new
                        {
                            Id = 32,
                            Class_id = 4,
                            Country_id = 1,
                            Date_of_birth = new DateTime(1960, 11, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Mauricio Fisher"
                        },
                        new
                        {
                            Id = 33,
                            Class_id = 4,
                            Country_id = 4,
                            Date_of_birth = new DateTime(1998, 3, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Mrs. Sheridan Cassin"
                        },
                        new
                        {
                            Id = 34,
                            Class_id = 3,
                            Country_id = 3,
                            Date_of_birth = new DateTime(1969, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Mrs. Erna Geo Rice I"
                        },
                        new
                        {
                            Id = 35,
                            Class_id = 1,
                            Country_id = 2,
                            Date_of_birth = new DateTime(1915, 2, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Jacynthe Dooley"
                        },
                        new
                        {
                            Id = 36,
                            Class_id = 3,
                            Country_id = 3,
                            Date_of_birth = new DateTime(1946, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Kendall Kautzer"
                        },
                        new
                        {
                            Id = 37,
                            Class_id = 1,
                            Country_id = 2,
                            Date_of_birth = new DateTime(2014, 11, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Catalina Opal Dach Sr."
                        },
                        new
                        {
                            Id = 38,
                            Class_id = 1,
                            Country_id = 4,
                            Date_of_birth = new DateTime(1925, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Cortez Murphy II"
                        },
                        new
                        {
                            Id = 39,
                            Class_id = 3,
                            Country_id = 4,
                            Date_of_birth = new DateTime(1962, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Flavie Hoppe III"
                        },
                        new
                        {
                            Id = 40,
                            Class_id = 3,
                            Country_id = 5,
                            Date_of_birth = new DateTime(2019, 11, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Dr. Deanna Sam Trantow DVM"
                        },
                        new
                        {
                            Id = 41,
                            Class_id = 1,
                            Country_id = 4,
                            Date_of_birth = new DateTime(1945, 4, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Jalon Kertzmann IV"
                        },
                        new
                        {
                            Id = 42,
                            Class_id = 5,
                            Country_id = 5,
                            Date_of_birth = new DateTime(1963, 9, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Camylle Jacobi"
                        },
                        new
                        {
                            Id = 43,
                            Class_id = 1,
                            Country_id = 2,
                            Date_of_birth = new DateTime(1966, 2, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Eladio Runolfsson"
                        },
                        new
                        {
                            Id = 44,
                            Class_id = 3,
                            Country_id = 3,
                            Date_of_birth = new DateTime(1943, 9, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Dr. Sophie Zemlak"
                        },
                        new
                        {
                            Id = 45,
                            Class_id = 4,
                            Country_id = 2,
                            Date_of_birth = new DateTime(1966, 8, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Leann Fadel"
                        },
                        new
                        {
                            Id = 46,
                            Class_id = 5,
                            Country_id = 5,
                            Date_of_birth = new DateTime(1929, 11, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Mr. Daphney Fleta Boyer"
                        },
                        new
                        {
                            Id = 47,
                            Class_id = 4,
                            Country_id = 1,
                            Date_of_birth = new DateTime(1960, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Miss Emma Schimmel IV"
                        },
                        new
                        {
                            Id = 48,
                            Class_id = 4,
                            Country_id = 5,
                            Date_of_birth = new DateTime(1974, 4, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Elian Connelly"
                        },
                        new
                        {
                            Id = 49,
                            Class_id = 2,
                            Country_id = 1,
                            Date_of_birth = new DateTime(1984, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Tad Kirlin"
                        },
                        new
                        {
                            Id = 50,
                            Class_id = 5,
                            Country_id = 2,
                            Date_of_birth = new DateTime(1989, 6, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Prof. Geovanni Vandervort"
                        },
                        new
                        {
                            Id = 51,
                            Class_id = 3,
                            Country_id = 5,
                            Date_of_birth = new DateTime(1905, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Dustin Kariane Schaefer III"
                        },
                        new
                        {
                            Id = 52,
                            Class_id = 1,
                            Country_id = 5,
                            Date_of_birth = new DateTime(1950, 7, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Willy O'Keefe"
                        },
                        new
                        {
                            Id = 53,
                            Class_id = 3,
                            Country_id = 1,
                            Date_of_birth = new DateTime(1978, 9, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Tobin Dayton Lubowitz PhD"
                        },
                        new
                        {
                            Id = 54,
                            Class_id = 4,
                            Country_id = 2,
                            Date_of_birth = new DateTime(2015, 7, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Maymie Dickinson"
                        },
                        new
                        {
                            Id = 55,
                            Class_id = 4,
                            Country_id = 4,
                            Date_of_birth = new DateTime(2005, 11, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Fred Bartell"
                        },
                        new
                        {
                            Id = 56,
                            Class_id = 1,
                            Country_id = 2,
                            Date_of_birth = new DateTime(1922, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Mr. Don Bins DVM"
                        },
                        new
                        {
                            Id = 57,
                            Class_id = 4,
                            Country_id = 5,
                            Date_of_birth = new DateTime(2008, 3, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Pedro Braun"
                        },
                        new
                        {
                            Id = 58,
                            Class_id = 1,
                            Country_id = 3,
                            Date_of_birth = new DateTime(1954, 9, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Antwon Jones"
                        },
                        new
                        {
                            Id = 59,
                            Class_id = 5,
                            Country_id = 1,
                            Date_of_birth = new DateTime(1987, 11, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Justina Paucek"
                        },
                        new
                        {
                            Id = 60,
                            Class_id = 1,
                            Country_id = 5,
                            Date_of_birth = new DateTime(1976, 2, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Jessyca Herzog"
                        },
                        new
                        {
                            Id = 61,
                            Class_id = 5,
                            Country_id = 5,
                            Date_of_birth = new DateTime(1948, 8, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Patrick Wiza PhD"
                        },
                        new
                        {
                            Id = 62,
                            Class_id = 2,
                            Country_id = 2,
                            Date_of_birth = new DateTime(1985, 4, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Prof. Jerod Adams PhD"
                        },
                        new
                        {
                            Id = 63,
                            Class_id = 4,
                            Country_id = 4,
                            Date_of_birth = new DateTime(1949, 5, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Gudrun Schiller"
                        },
                        new
                        {
                            Id = 64,
                            Class_id = 1,
                            Country_id = 1,
                            Date_of_birth = new DateTime(1993, 11, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Nelle Marquardt"
                        },
                        new
                        {
                            Id = 65,
                            Class_id = 4,
                            Country_id = 1,
                            Date_of_birth = new DateTime(1952, 6, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Jeramy Goodwin"
                        },
                        new
                        {
                            Id = 66,
                            Class_id = 1,
                            Country_id = 3,
                            Date_of_birth = new DateTime(1937, 9, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Kylee Elouise Schiller DVM"
                        },
                        new
                        {
                            Id = 67,
                            Class_id = 4,
                            Country_id = 3,
                            Date_of_birth = new DateTime(1951, 10, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Alden White"
                        },
                        new
                        {
                            Id = 68,
                            Class_id = 3,
                            Country_id = 4,
                            Date_of_birth = new DateTime(2007, 10, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Chauncey Block"
                        },
                        new
                        {
                            Id = 69,
                            Class_id = 3,
                            Country_id = 5,
                            Date_of_birth = new DateTime(1960, 11, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Mrs. Reid Judd Lang II"
                        },
                        new
                        {
                            Id = 70,
                            Class_id = 5,
                            Country_id = 5,
                            Date_of_birth = new DateTime(1970, 10, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Zechariah Lubowitz"
                        },
                        new
                        {
                            Id = 71,
                            Class_id = 5,
                            Country_id = 2,
                            Date_of_birth = new DateTime(2004, 9, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Mrs. Wilton Schmeler"
                        },
                        new
                        {
                            Id = 72,
                            Class_id = 4,
                            Country_id = 5,
                            Date_of_birth = new DateTime(1947, 1, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Lonnie Pacocha"
                        },
                        new
                        {
                            Id = 73,
                            Class_id = 2,
                            Country_id = 2,
                            Date_of_birth = new DateTime(2008, 11, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Lorenz Beahan"
                        },
                        new
                        {
                            Id = 74,
                            Class_id = 2,
                            Country_id = 3,
                            Date_of_birth = new DateTime(1959, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Shaylee Vandervort"
                        },
                        new
                        {
                            Id = 75,
                            Class_id = 3,
                            Country_id = 4,
                            Date_of_birth = new DateTime(1960, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Dr. Cleta Gusikowski"
                        },
                        new
                        {
                            Id = 76,
                            Class_id = 2,
                            Country_id = 5,
                            Date_of_birth = new DateTime(1914, 8, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Prof. Theresa Metz DVM"
                        },
                        new
                        {
                            Id = 77,
                            Class_id = 2,
                            Country_id = 4,
                            Date_of_birth = new DateTime(1992, 2, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Emilie Dach"
                        },
                        new
                        {
                            Id = 78,
                            Class_id = 4,
                            Country_id = 2,
                            Date_of_birth = new DateTime(1952, 9, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Casper McLaughlin"
                        },
                        new
                        {
                            Id = 79,
                            Class_id = 2,
                            Country_id = 5,
                            Date_of_birth = new DateTime(1940, 2, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Prof. Damon Prosacco"
                        },
                        new
                        {
                            Id = 80,
                            Class_id = 5,
                            Country_id = 3,
                            Date_of_birth = new DateTime(1992, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Brody Kunze"
                        },
                        new
                        {
                            Id = 81,
                            Class_id = 2,
                            Country_id = 4,
                            Date_of_birth = new DateTime(2011, 10, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Miss Nedra Kling II"
                        },
                        new
                        {
                            Id = 82,
                            Class_id = 1,
                            Country_id = 1,
                            Date_of_birth = new DateTime(1969, 7, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Jamaal Wendy Wolf Sr."
                        },
                        new
                        {
                            Id = 83,
                            Class_id = 4,
                            Country_id = 5,
                            Date_of_birth = new DateTime(1960, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Serena Hyatt"
                        },
                        new
                        {
                            Id = 84,
                            Class_id = 4,
                            Country_id = 4,
                            Date_of_birth = new DateTime(1975, 7, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Quincy O'Connell"
                        },
                        new
                        {
                            Id = 85,
                            Class_id = 3,
                            Country_id = 3,
                            Date_of_birth = new DateTime(2006, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Ms. Cathryn Virgil Franecki"
                        },
                        new
                        {
                            Id = 86,
                            Class_id = 1,
                            Country_id = 1,
                            Date_of_birth = new DateTime(1961, 8, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Norval Wintheiser"
                        },
                        new
                        {
                            Id = 87,
                            Class_id = 5,
                            Country_id = 5,
                            Date_of_birth = new DateTime(1995, 2, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Magali Beier"
                        },
                        new
                        {
                            Id = 88,
                            Class_id = 5,
                            Country_id = 5,
                            Date_of_birth = new DateTime(1960, 9, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Miss Ally Leanne Boehm V"
                        },
                        new
                        {
                            Id = 89,
                            Class_id = 5,
                            Country_id = 1,
                            Date_of_birth = new DateTime(1991, 3, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Jaida Balistreri"
                        },
                        new
                        {
                            Id = 90,
                            Class_id = 4,
                            Country_id = 4,
                            Date_of_birth = new DateTime(1960, 5, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Neva Paucek"
                        },
                        new
                        {
                            Id = 91,
                            Class_id = 3,
                            Country_id = 1,
                            Date_of_birth = new DateTime(2013, 3, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Zoe Rempel Jr."
                        },
                        new
                        {
                            Id = 92,
                            Class_id = 1,
                            Country_id = 3,
                            Date_of_birth = new DateTime(1976, 2, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Mrs. Benny Murazik MD"
                        },
                        new
                        {
                            Id = 93,
                            Class_id = 3,
                            Country_id = 1,
                            Date_of_birth = new DateTime(1962, 9, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Vivien McClure"
                        },
                        new
                        {
                            Id = 94,
                            Class_id = 5,
                            Country_id = 2,
                            Date_of_birth = new DateTime(1911, 12, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Miss Olin Cooper Mosciski III"
                        },
                        new
                        {
                            Id = 95,
                            Class_id = 1,
                            Country_id = 2,
                            Date_of_birth = new DateTime(1997, 10, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Kylee Marianna Romaguera I"
                        },
                        new
                        {
                            Id = 96,
                            Class_id = 2,
                            Country_id = 1,
                            Date_of_birth = new DateTime(2018, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Dagmar O'Kon"
                        },
                        new
                        {
                            Id = 97,
                            Class_id = 5,
                            Country_id = 4,
                            Date_of_birth = new DateTime(1960, 1, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Maud Johnson Smith Sr."
                        },
                        new
                        {
                            Id = 98,
                            Class_id = 4,
                            Country_id = 1,
                            Date_of_birth = new DateTime(2019, 4, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Sylvester Kovacek"
                        },
                        new
                        {
                            Id = 99,
                            Class_id = 3,
                            Country_id = 4,
                            Date_of_birth = new DateTime(1943, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Viola Howell"
                        },
                        new
                        {
                            Id = 100,
                            Class_id = 5,
                            Country_id = 1,
                            Date_of_birth = new DateTime(1992, 6, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            name = "Jean Bednar DDS"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
